### ISSUE TITLE
Use Heroku Release Phase rather than a custom buildpack

### ISSUE THREAD

**Issue by MrHubble** [ankane/shorts#7]
Thank you for the extremely helpful guide to using Rails with Heroku.

In the **Debug** section, you recommend using a custom buildpack. The [buildpack-ruby-rake-deploy-tasks gem](https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks) would now be deprecated because [Release Phase](https://devcenter.heroku.com/articles/release-phase) is no longer in beta:

![Screen Shot 2019-06-06 at 2 48 04 pm](https://user-images.githubusercontent.com/2251631/59007536-1c0c7480-886a-11e9-9b3e-79304fc2ab49.png)

Would you now recommend using **Release Phase**? I ask with regards to migrations in particular. I use your fantastic `strong_migrations` gem so I think I will avoid this [design consideration](https://devcenter.heroku.com/articles/release-phase#design-considerations):

![Screen Shot 2019-06-06 at 2 49 26 pm](https://user-images.githubusercontent.com/2251631/59007567-570ea800-886a-11e9-8868-b4f88538305c.png)

**Comment by ankane** [comment]
Hey @MrHubble, I haven't tried release phases, but it looks like you should be able to replace the custom buildpack with a Procfile like:

```
release: bin/rails preload db:migrate
```

Both the custom buildpack and release phases should be the same with regards to migrations.

Overall, the advice of "use transactions for database migrations" is good, which is why Rails does it by default. However, if you want to zero downtime, some database tasks will need to be run outside a database transaction (like adding a concurrent index). These operations can potentially fail and leave the database in a safe but undesired state. If that happens, you'll need to correct it manually before you run the migration again.

For instance, if a concurrent index fails, you'll be left with an invalid index. The database knows it's invalid so it won't attempt to use it, but you'll need to manually drop it so the migration doesn't fail when it tries to run again on your next deploy.

**Comment by ankane** [comment]
Tried out release phase tasks and it worked well, so updated the post. Thanks for the suggestion 👍
